# Generated by Django 4.2.20 on 2025-04-23 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Аллергия')),
            ],
        ),
        migrations.CreateModel(
            name='DietType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Тип диеты')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ограничение по стоимости')),
                ('count_of_persons', models.IntegerField(default=1, verbose_name='Количество персон')),
                ('breakfast', models.BooleanField(verbose_name='Завтрак')),
                ('lunch', models.BooleanField(verbose_name='Обед')),
                ('dinner', models.BooleanField(verbose_name='Ужин')),
                ('dessert', models.BooleanField(verbose_name='Десерт')),
                ('subscription_end_date', models.DateField(verbose_name='Дата окончания подписки')),
                ('allergies', models.ManyToManyField(blank=True, to='planner.allergy', verbose_name='Аллергии')),
                ('diet_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.diettype', verbose_name='Тип диеты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
