# Generated by Django 4.2.20 on 2025-04-23 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('callories', models.IntegerField(verbose_name='Калорийность')),
                ('allergens', models.ManyToManyField(blank=True, to='planner.allergy', verbose_name='Аллергены')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Описание блюда')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото блюда')),
                ('diet_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.diettype', verbose_name='Тип диеты')),
            ],
        ),
    ]
