# Generated by Django 4.2.20 on 2025-04-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_dish_dish_type_ingredient_unit_alter_dish_diet_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='dish_type',
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('dessert', 'Десерт')], default='lunch', max_length=50, verbose_name='Категория блюда'),
        ),
    ]
