# Generated by Django 4.2.20 on 2025-04-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_remove_dish_dish_type_dish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='callories',
            field=models.FloatField(verbose_name='Калорийность'),
        ),
    ]
