# Generated by Django 4.2.20 on 2025-04-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_ingredient_callories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='callories',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Калорийность'),
        ),
    ]
