# Generated by Django 4.2.20 on 2025-04-24 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_ingredient_callories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='breakfast',
            field=models.BooleanField(default=True, verbose_name='Завтрак'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='budget_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ограничение по стоимости'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dessert',
            field=models.BooleanField(default=False, verbose_name='Десерт'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='diet_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.diettype', verbose_name='Тип диеты'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dinner',
            field=models.BooleanField(default=True, verbose_name='Ужин'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lunch',
            field=models.BooleanField(default=True, verbose_name='Обед'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания подписки'),
        ),
    ]
