# Generated by Django 4.2.20 on 2025-04-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_alter_userprofile_breakfast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='recipe',
            field=models.TextField(blank=True, default='', verbose_name='Рецепт приготовления'),
        ),
    ]
