# Generated by Django 4.2.20 on 2025-04-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_dish_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(default='dishes/default.jpg', upload_to='dishes/', verbose_name='Фото блюда'),
        ),
    ]
