# Generated by Django 4.2.20 on 2025-04-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_alter_dish_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Фото блюда'),
        ),
    ]
